package com.framework.exception;

public class DataAccessErrorMessage {
	 /**
     * 保存数据出错
     */
    public static final String SAVE_EXCEPTION = "保存数据出错";

    /**
     * 更新数据出错
     */
    public static final String UPDATE_EXCEPTION = "更新数据出错";

    /**
     * 删除数据出错
     */
    public static final String DELETE_EXCEPTION = "删除数据出错";

    /**
     * 查找一条数据出错
     */
    public static final String FIND_EXCEPTION = "查找单条数据出错";

    /**
     * 查询多条数据出错
     */
    public static final String LIST_EXCEPTION = "查询多条数据出错";

    /**
     * 分页查询数据出错
     */
    public static final String FIND_BY_PAGE_EXCEPTION = "分页查询数据出错";

    /**
     * 统计数据数量出错
     */
    public static final String COUNT_EXCEPTION = "统计数据数量出错";

    /**
     * 统计数据最大值出错
     */
    public static final String MAX_EXCEPTION = "统计数据最大值出错";

    /**
     * 执行语句出错
     */
    public static final String EXECUTE_EXCEPTION = "执行语句出错";

    /**
     * 查询所有数据出错
     */
    public static final String FIND_ALL_EXCEPTION = "查询所有数据出错";

    /**
     * 执行存储过程异常
     */
    public static final String EXECUTE_CALL_EXCEPTION = "执行存储过程异常";
}
